import type { Metadata } from "next";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import { Noto_Sans_Display } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto = Noto_Sans_Display({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={noto.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
